---
collections:
#- name: netapp.ontap
#  version: '22.3'
- name: community.general
#- name: device42.d42
#  version: 1.1.2
#  source: https://galaxy.ansible.com/
#- name: ibm.power_ibmi
#  type: git
#- f5networks.f5_modules
