---
- name: list all the active scheduled jobs from each organization
  hosts: localhost
  gather_facts: false
  collections:
  - ansible.controller

  tasks:
#    - name: Query for all schedules
#      ansible.builtin.set_fact:
#        scheduled_with_next_run: "{{ query('ansible.controller.controller_api', 'schedules', host=10.0.78.52, username=admin, password=ansible, verify_ssl=False, return_all=true) | list }}"

    - name: Query for all schedules
      ansible.builtin.set_fact:
        scheduled_with_next_run: "{{ query('ansible.controller.controller_api', 'schedules',
                                              host='https://10.0.78.232',
                                              username='fry',
                                              password='fry',
                                              verify_ssl=False,
                                              return_all=true,
                                              max_objects=50000)
                                  | list }}"
