---
- name: Change request template
  hosts: all
  gather_facts: no
  tasks:
    - name: Create the directory in ansible controller
      file:
        path: /test/dir/045/
        state: directory
        mode: '0755'
        owner: cloud-user
        group: cloud-user
      delegate_to: localhost
