---
- name: Set a custom fact
  hosts: all
  gather_facts: true

  tasks:

    - name: Set the fact
      set_fact:
        foo: bar
        cachable: true

    - name: Debug the fact
      debug:
        msg: "{{ foo }}"
