---
- name: Fetch test in AAP 2.1.2
  hosts: all
  gather_facts: true
  become: true
  ansible_user: vagrant
  ansible_password: vagrant
  tasks:
    - name: use the fetch module
      fetch:
        src: /etc/hosts
        dest: /opt/collect/
