- name: file creation test
  hosts: localhost
  gather_facts: false
  
  tasks:
  - name: Create a tmp_files directory
    ansible.builtin.file:
      path: /tmp/tmp_files
      state: directory
      #owner: awx
      #group: awx
      mode: 0755
