- name: file creation test
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Create a tmp_files directory
    ansible.builtin.file:
      path: /tmp/tmp_files
      state: directory
      owner: awx
      group: awx
      mode: 0755
    delegate_to: 10.42.0.20
