---
- name: Hello World!
  hosts: all
  vars:
    foo: 
      lolo: lele 
  tasks:
 
  - name: Check SSH
    shell: "echo Hello World"

  - name: Hello World!
    debug: 
      msg: "Hello World!!! Server {{ ansible_hostname }} var foo={{ foo.lolo }}"
    loop: "{{ range(1, 40000) | list }}"
