
- name: IBM i Test
  hosts: localhost
  collections:
    ibm.power_ibmi
  
  tasks:
  - name: Create a library by using CL command CRTLIB
    ibm.power_ibmi.ibmi_cl_command:
      cmd: 'CRTLIB LIB(TESTLIB)'
      become_user: 'USER1'
      become_user_password: 'yourpassword'
