---
# CORRECT CODE:
#- hosts: localhost
#  connection: ssh
#  gather_facts: false
#  tasks:
#  - name: first playbook
#    ping:
#- import_playbook: sub_playbook.yml

# WRONG CODE:
- hosts: localhost
  connection: ssh
  gather_facts: false
  tasks:
  - ping:
  - import_playbook:
    name: sub_playbook.yml
