---
- name: Long Playbook
  hosts: all
  strategy: "{{ pb_strategy | default(omit) }}"

  vars:
    sleep_time: 30
    loop_count: 100

  tasks:
  - name: Sleep Command Loop
    ansible.builtin.command: sleep {{ sleep_time }}
    changed_when: false
    loop: "{{ range(0, loop_count) | list }}"
      
  - name: Display Message
    ansible.builtin.debug:
      msg: Reached the end!
