- name: /usr/bin/mailx test
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Send mail if preflight has failed state
    ansible.builtin.shell: 
      cmd: 'echo "test" | /usr/bin/mailx -s "localhost: Preflight check failed" test@test.com'
    delegate_to: localhost
