- name: netapp module test
  hosts: all
  gather_facts: false
  
  tasks:
  - name: ontap probe_port test
    na_ontap_interface:
      #<<: *input
      hostname: 10.42.0.198
      username: test
      password: test
      use_rest: always
      interface_name: test1
      home_port: 13
      home_node: test
      role: data
      protocols: nfs,cifs
      admin_status: up
      probe_port: 1331
      failover_policy: system-defined
      is_auto_revert: true
      address: 10.42.0.198
      netmask: test
      vserver: 10.42.0.198
