---
- name: Testing password_hash function
  hosts: all
  gather_facts: false
  #connection: local
  tasks:
  - name: Update local password test_user
    user:
      name: test_user
      password: "{{ lookup('env','test_password')  | password_hash('sha512') }}"
