---
- name: Ping test for local connection
  hosts: all
  gather_facts: false
  #connection: local
  tasks:
  - name: ping
    ping:
    #delegate_to: localhost
    tags: always
    when: image_sku is search ("Windows")
