---
- name: Ping test for local connection
  hosts: all
  gather_facts: true
  #connection: local
  tasks:
  - name: ping
    ping:
    #delegate_to: localhost
    environment:
      keep_remote_files: true
