- name: synchronize module test
  hosts: all
  tasks:
  
  - name: Copy test file
    synchronize:
      src: /home/ansible/test.txt
      dest: /home/ansible/
      mode: push
    delegate_to: localhost
    #become: true
