---
- name: Date and time test
  hosts: localhost
  gather_facts: false
  #connection: local
  
  tasks:
  
  - name: Set timezone
    timezone:
      #name: US/Pacific
      name: America/New_York
    become: yes
    become_method: sudo
      
  - name: Get date and time
    shell: date '+%Y-%m-%d %H:%M:%S %Z' --date='24 hours ago'
    register: time
    
#  - name: Print date and time
#    debug:
#      time
