---
- name: Date and time test
  hosts: localhost
  gather_facts: false
  #connection: local
  
  tasks:
  - name: Set timezone
    timezone:
      name: US/Pacific
  - name: Get date and time
    shell: TZ='US/Pacific' date '+%Y-%m-%d %H:%M:%S %Z' --date='24 hours ago'
    register: time
    
#  - name: Print date and time
#    debug:
#      time
