---
- hosts: all

  vars:
    test_file: test.tar
    local_src_path: /tmp/testperms/test

  tasks: 

    - name: Copy and untar files
      ansible.builtin.unarchive:
        src: "{{ local_src_path }}/{{ test_file }}"
        dest: /etc
