---
- hosts: all

  vars:
    test_file: test.tar
    #local_src_path: /tmp/testperms/test
    local_src_path: /home/vagrant/test

  tasks: 

    - name: Unarchive tar file
      unarchive:
        src: "{{ local_src_path }}/{{ test_file }}"
        dest: /etc/test/
        copy: yes

#    - name: Copy tar file
#      copy:
#        src: "{{ local_src_path }}/{{ test_file }}"
#        dest: /etc
