---
- hosts: all

  vars:
    test_file: test.tar
    local_src_path: /tmp/testperms/test

  tasks: 

    - name: Unarchive tar file
      unarchive:
        src: "{{ local_src_path }}/{{ test_file }}"
        dest: /etc
        copy: yes

    - name: Copy tar file
      copy:
        src: "{{ local_src_path }}/{{ test_file }}"
        dest: /etc
