---
- name: Variable Survey Test
  hosts: localhost
  gather_facts: false
  vars:
    sn_host: "{{ sn_host }}"
    sn_user: "{{ sn_user }}" 
    sn_pass: "{{ sn_pass }}"
  
  tasks:

  - debug:
      msg: "The hostname is {{ sn_host }}, the username is {{ sn_user }}, and the password is {{ sn_pass }}"
