- name: Example ansible play that yum update and reboot
  hosts: all
  #ignore_unreachable: true
  #remote_user: ansible
  gather_facts: no
     
  tasks:
    - name: Perform dnf update of all packages
      shell: "dnf update chrony -y"
