- name: Yum update test playbook
  hosts: all
  gather_facts: false
  
  tasks:
#  - name: Perform yum update
#    ansible.builtin.yum:
#      name: '*'
#      exclude:
#        - couch*
#        - nodejs*
#        - npm*
#        - newrelic*
#        - percona*
#      state: latest
#      lock_timeout: 180
#      update_cache: yes

  - name: Perform yum update
    ansible.builtin.yum:
      name: 'chrony'
      state: latest
      lock_timeout: 180
      update_cache: yes
