---
- name: Listen for events on a webhook from webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
  rules:
    - name: Read raw payload 
      condition: event.payload.message == "Ansible is super cool!"
        #any:
          #- event.meta is defined
          #- event.payload is defined
          #- event.payload.message == "Ansible is super cool!"
      action: 
        debug:
          msg: "The value is {{ event.payload.message }}"


# Trigger rulebook with the following command:
# curl --header "Content-Type: application/json" --request POST --data '{"message":"Ansible is super cool"}' http://$EDA_CONTROLLER:5002
