- name: Run job template
  hosts: all
  gather_facts: true
  
  sources:
    - ansible.eda.webhook:
        port: 5000
      filters:
        - ansible.eda.insert_hosts_to_meta:
           host_path: "payload.meta.hosts"
           path_separator: "." 
           host_separator: ";" 
        
  rules:
    - name: "Host specific rule"
      condition:
        all:
          - fact.ansible_os_family == "linux"
          - fact.meta.hosts == "my-host"
          - event.i == 4
          
      action:
        run_job_template:
          name: Ping
          organization: Default
          job_args:
            limit: "{{ payload.meta.hosts }}"
