---
# This rulebooks is for testing an issue in case 03924246

- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
   - name: range
     ansible.eda.range:
        limit: 5
  ## Define the conditions we are looking for
  rules:
    #- name: Check cockpit
    #  condition: event.payload.message == "cockpit is down"
    - name: Launch JT with a survey
      condition: event.i == 1
  ## Define the action we should take should the condition be met
      action:
        run_job_template:
          name: "Variable Survey Test - Rulebook Activation"
          organization: Default
          job_args:
            extra_vars:
              #sn_create_short_description: "{{event.payload.hostname}} - cockpit is down"
              sn_host: 'host1'
              sn_user: 'other_user'
              sn_pass: '67890'
