---
# This rulebooks is for testing an issue in case 03924246

- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Launch the job
      condition: event.payload.message == "launch"

      action:
        run_job_template:
          name: "Variable Survey Test - Rulebook Activation"
          organization: Default
          job_args:
            extra_vars:
              sn_host: 'host2'
              sn_user: 'other_user2'
              sn_pass: 'new_password'
