---
- name: Listen for events on webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool!"
      action:
        run_job_template:
          name: 'Demo Job Template'
          organization: Default
          #job_args:
            #extra_vars:
              #message: from eda
              #sender: "{{ event.payload.sender }}"
              #sleep: 1

# Trigger rulebook with the following command:
# curl --header "Content-Type: application/json" --request POST --data '{"message":"Ansible is super cool"}' http://$EDA_CONTROLLER:5001
